---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: containers
platforms:
  - name: sudoers01
    image: rockylinux:9
    pre_build_image: false
    # privileged: true
    # command: "/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
