---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Read files
      ansible.builtin.shell: cat /etc/sudoers.d/*
      changed_when: false
      register: file_content

    - name: Print file content
      ansible.builtin.debug:
        msg: "{{ file_content.stdout_lines }}"
