name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: robertdebock/molecule-action@d3e37309fc9c287d6a3507d172520d37df0e2dda # 6.0.1
        # with:
        #   scenario: ${{ matrix.scenario }}
